# Generated by Django 4.2 on 2025-04-28 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_toolcategory_toolcategorytranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='converter.toolcategory'),
            preserve_default=False,
        ),
    ]

