# Generated by Django 4.2 on 2025-04-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_tool_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolcategorytranslation',
            name='title',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
