# Generated by Django 4.2 on 2025-04-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_alter_tool_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
