# Generated by Django 4.2 on 2025-04-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0007_toolcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcategory',
            name='js_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
